script:
    - ./travis-enforce.sh
notifications:
    irc:
        channels:
            - "irc.freenode.net#hammerspoon"
        template:
            - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
        use_notice: true
        skip_join: true

