name: PR Results

on:
  workflow_run:
    workflows: ["PR"]
    types:
      - completed

jobs:
  publish:
    name: "Publish PR Annotations"
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var fs = require('fs');
            var path = require('path');
            var artifacts_path = path.join('${{github.workspace}}', 'artifacts')
            fs.mkdirSync(artifacts_path, { recursive: true })

            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });

            for (const artifact of artifacts.data.artifacts) {
              var download = await github.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
              });
              var artifact_path = path.join(artifacts_path, `${artifact.name}.zip`)
                fs.writeFileSync(artifact_path, Buffer.from(download.data));
                console.log(`Downloaded ${artifact_path}`);
            }
      - name: Extract Artifacts
        run: |
          for file in artifacts/*.zip
          do
            if [ -f "$file" ]
            then
              dir="${file/%.zip/}"
              mkdir -p "$dir"
              unzip -d "$dir" "$file"
            fi
          done
      - name: Show Artifacts
        run: find artifacts -ls

      # Since proper annotations don't work in this context, we'll just add the JSON annotation output as a comment
      - name: Check for a PR number
        id: check_pr_number
        uses: andstor/file-existence-action@v1
        with:
          files: "artifacts/pr_num.txt/pr_num.txt"
      - name: Add annotations output as a PR comment
        if: steps.check_pr_number.outputs.files_exists == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const pr_num = fs.readFileSync('artifacts/pr_num.txt/pr_num.txt', 'utf8')
            const annotations = fs.readFileSync('artifacts/annotations.json/annotations.json', 'utf8')
            github.rest.issues.createComment({
              issue_number: pr_num,
              owner: 'hammerspoon',
              repo: 'Spoons',
              body: '```' + annotations + '```'
            })

          # This really ought to work, but the annotations disappear into the ether
          #      - name: Publish Docstring Annotations
          #        uses: cmsj/annotations-action@v0.4.0-cmsj-alpha
          #        with:
          #          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          #          title: "Docstrings linter"
          #          input: "artifacts/annotations.json/annotations.json"
          #          commit: ${{ github.event.workflow_run.head_sha }}

